# Generated by Django 3.1.7 on 2021-03-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='events',
        ),
    ]
