# Generated by Django 3.1.7 on 2021-02-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='todolist',
            new_name='todo',
        ),
    ]
