# Generated by Django 3.1.7 on 2021-03-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('e1', models.CharField(max_length=20)),
                ('e2', models.CharField(max_length=20)),
                ('e3', models.CharField(max_length=20)),
            ],
        ),
    ]
