# Generated by Django 3.1.7 on 2021-03-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='item',
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='todolist',
        ),
    ]
