# Generated by Django 3.1.7 on 2021-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_events_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='schoolname',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='section',
            field=models.IntegerField(default=0),
        ),
    ]
