# Generated by Django 3.1.7 on 2021-04-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210426_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='discord_id',
        ),
        migrations.AlterField(
            model_name='events',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='section',
            field=models.IntegerField(null=True),
        ),
    ]
