# Generated by Django 3.1.7 on 2021-04-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210426_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='section',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
