# Generated by Django 3.1.7 on 2021-04-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210426_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='number',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
