# Generated by Django 3.1.7 on 2021-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210426_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='code',
            field=models.CharField(default='*', max_length=100),
        ),
    ]
